name = "HarleyColonies"
author = "Alan Young"
version = "v0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30e6054afddf3e1a8e77d75c69a01d71675175c8ad367261e561450832a26416"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
