name = "HarleyColonies"
author = "Alan Young"
version = "v0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06416498f31d879df20ad8c1b7e7cc140cbde593f2027576f334de1708cf301c"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
