name = "HarleyColonies"
author = "Alan Young"
version = "v0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01c23ca522e2cccb3b33f56334be1b91a3237f39e2e91ee23bab4b9031209192"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
