name = "HarleyColonies"
author = "Alan Young"
version = "v0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "deff9c44ff3446d5798164de552d63be47aa28efa9b763bd595320d444a661e9"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
