name = "HarleyColonies"
author = "Alan Young"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa9b9c555783944816023da19c296a8370ed92ac52183f206b1ace194a766060"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
