name = "HarleyColonies"
author = "Alan Young"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4414506fe0f6cd5d2b2c365a7497feafcc4170c5f756d6ab2876bd86220d703b"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
