name = "HarleyColonies"
author = "Alan Young"
version = "v0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ea50ca32f20ca114399b796d19d85f0a8db425ada66c30157e9471721c82cb2"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
