name = "HarleyColonies"
author = "Alan Young"
version = "v0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2dc5ba281fc4c1b89c7bfb5447f0ca8722198461896b03c46827d09838c0015"

[versions]
forge = "47.2.32"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
