settings:
  - name: acceptableThrowawayItems
    group: unknown
    default:
    description: |

  - name: allowBreak
    group: unknown
    default:
    description: |

  - name: allowBreakAnyway
    group: unknown
    default:
    description: |

  - name: allowDiagonalAscend
    group: unknown
    default:
    description: |

  - name: allowDiagonalDescend
    group: unknown
    default:
    description: |

  - name: allowDownward
    group: unknown
    default:
    description: |

  - name: allowInventory
    group: unknown
    default:
    description: |

  - name: allowJumpAt256
    group: unknown
    default:
    description: |

  - name: allowOnlyExposedOres
    group: unknown
    default:
    description: |

  - name: allowOnlyExposedOresDistance
    group: unknown
    default:
    description: |

  - name: allowOvershootDiagonalDescend
    group: unknown
    default:
    description: |

  - name: allowParkour
    group: unknown
    default:
    description: |

  - name: allowParkourAscend
    group: unknown
    default:
    description: |

  - name: allowParkourPlace
    group: unknown
    default:
    description: |

  - name: allowPlace
    group: unknown
    default:
    description: |

  - name: allowSprint
    group: unknown
    default:
    description: |

  - name: allowVines
    group: unknown
    default:
    description: |

  - name: allowWalkOnBottomSlab
    group: unknown
    default:
    description: |

  - name: allowWaterBucketFall
    group: unknown
    default:
    description: |

  - name: allSettings
    group: unknown
    default:
    description: |

  - name: antiCheatCompatibility
    group: unknown
    default:
    description: |

  - name: assumeExternalAutoTool
    group: unknown
    default:
    description: |

  - name: assumeSafeWalk
    group: unknown
    default:
    description: |

  - name: assumeStep
    group: unknown
    default:
    description: |

  - name: assumeWalkOnLava
    group: unknown
    default:
    description: |

  - name: assumeWalkOnWater
    group: unknown
    default:
    description: |

  - name: autoTool
    group: unknown
    default:
    description: |

  - name: avoidance
    group: unknown
    default:
    description: |

  - name: avoidBreakingMultiplier
    group: unknown
    default:
    description: |

  - name: avoidUpdatingFallingBlocks
    group: unknown
    default:
    description: |

  - name: axisHeight
    group: unknown
    default:
    description: |

  - name: backfill
    group: unknown
    default:
    description: |

  - name: backtrackCostFavoringCoefficient
    group: unknown
    default:
    description: |

  - name: blacklistClosestOnFailure
    group: unknown
    default:
    description: |

  - name: blockBreakAdditionalPenalty
    group: unknown
    default:
    description: |

  - name: blockPlacementPenalty
    group: unknown
    default:
    description: |

  - name: blockReachDistance
    group: unknown
    default:
    description: |

  - name: blocksToAvoid
    group: unknown
    default:
    description: |

  - name: blocksToAvoidBreaking
    group: unknown
    default:
    description: |

  - name: blocksToDisallowBreaking
    group: unknown
    default:
    description: |

  - name: breakCorrectBlockPenaltyMultiplier
    group: unknown
    default:
    description: |

  - name: breakFromAbove
    group: unknown
    default:
    description: |

  - name: builderTickScanRadius
    group: unknown
    default:
    description: |

  - name: buildIgnoreBlocks
    group: unknown
    default:
    description: |

  - name: buildIgnoreDirection
    group: unknown
    default:
    description: |

  - name: buildIgnoreExisting
    group: unknown
    default:
    description: |

  - name: buildIgnoreProperties
    group: unknown
    default:
    description: |

  - name: buildInLayers
    group: unknown
    default:
    description: |

  - name: buildOnlySelection
    group: unknown
    default:
    description: |

  - name: buildRepeat
    group: unknown
    default:
    description: |

  - name: buildRepeatCount
    group: unknown
    default:
    description: |

  - name: buildRepeatSneaky
    group: unknown
    default:
    description: |

  - name: buildSkipBlocks
    group: unknown
    default:
    description: |

  - name: buildSubstitutes
    group: unknown
    default:
    description: |

  - name: buildValidSubstitutes
    group: unknown
    default:
    description: |

  - name: byLowerName
    group: unknown
    default:
    description: |

  - name: cachedChunksExpirySeconds
    group: unknown
    default:
    description: |

  - name: cachedChunksOpacity
    group: unknown
    default:
    description: |

  - name: cancelOnGoalInvalidation
    group: unknown
    default:
    description: |

  - name: censorCoordinates
    group: unknown
    default:
    description: |

  - name: censorRanCommands
    group: unknown
    default:
    description: |

  - name: chatControl
    group: unknown
    default:
    description: |

  - name: chatControlAnyway
    group: unknown
    default:
    description: |

  - name: chatDebug
    group: unknown
    default:
    description: |

  - name: chunkCaching
    group: unknown
    default:
    description: |

  - name: colorBestPathSoFar
    group: unknown
    default:
    description: |

  - name: colorBlocksToBreak
    group: unknown
    default:
    description: |

  - name: colorBlocksToPlace
    group: unknown
    default:
    description: |

  - name: colorBlocksToWalkInto
    group: unknown
    default:
    description: |

  - name: colorCurrentPath
    group: unknown
    default:
    description: |

  - name: colorGoalBox
    group: unknown
    default:
    description: |

  - name: colorInvertedGoalBox
    group: unknown
    default:
    description: |

  - name: colorMostRecentConsidered
    group: unknown
    default:
    description: |

  - name: colorNextPath
    group: unknown
    default:
    description: |

  - name: colorSelection
    group: unknown
    default:
    description: |

  - name: colorSelectionPos1
    group: unknown
    default:
    description: |

  - name: colorSelectionPos2
    group: unknown
    default:
    description: |

  - name: considerPotionEffects
    group: unknown
    default:
    description: |

  - name: costHeuristic
    group: unknown
    default:
    description: |

  - name: costVerificationLookahead
    group: unknown
    default:
    description: |

  - name: cutoffAtLoadBoundary
    group: unknown
    default:
    description: |

  - name: desktopNotifications
    group: unknown
    default:
    description: |

  - name: disableCompletionCheck
    group: unknown
    default:
    description: |

  - name: disconnectOnArrival
    group: unknown
    default:
    description: |

  - name: distanceTrim
    group: unknown
    default:
    description: |

  - name: doBedWaypoints
    group: unknown
    default:
    description: |

  - name: doDeathWaypoints
    group: unknown
    default:
    description: |

  - name: echoCommands
    group: unknown
    default:
    description: |

  - name: enterPortal
    group: unknown
    default:
    description: |

  - name: exploreChunkSetMinimumSize
    group: unknown
    default:
    description: |

  - name: exploreForBlocks
    group: unknown
    default:
    description: |

  - name: exploreMaintainY
    group: unknown
    default:
    description: |

  - name: extendCacheOnThreshold
    group: unknown
    default:
    description: |

  - name: fadePath
    group: unknown
    default:
    description: |

  - name: failureTimeoutMS
    group: unknown
    default:
    description: |

  - name: followOffsetDirection
    group: unknown
    default:
    description: |

  - name: followOffsetDistance
    group: unknown
    default:
    description: |

  - name: followRadius
    group: unknown
    default:
    description: |

  - name: forceInternalMining
    group: unknown
    default:
    description: |

  - name: freeLook
    group: unknown
    default:
    description: |

  - name: goalBreakFromAbove
    group: unknown
    default:
    description: |

  - name: goalRenderLineWidthPixels
    group: unknown
    default:
    description: |

  - name: incorrectSize
    group: unknown
    default:
    description: |

  - name: internalMiningAirException
    group: unknown
    default:
    description: |

  - name: itemSaver
    group: unknown
    default:
    description: |

  - name: itemSaverThreshold
    group: unknown
    default:
    description: |

  - name: jumpPenalty
    group: unknown
    default:
    description: |

  - name: layerHeight
    group: unknown
    default:
    description: |

  - name: layerOrder
    group: unknown
    default:
    description: |

  - name: legitMine
    group: unknown
    default:
    description: |

  - name: legitMineIncludeDiagonals
    group: unknown
    default:
    description: |

  - name: legitMineYLevel
    group: unknown
    default:
    description: |

  - name: logAsToast
    group: unknown
    default:
    description: |

  - name: logger
    group: unknown
    default:
    description: |

  - name: mapArtMode
    group: unknown
    default:
    description: |

  - name: maxCachedWorldScanCount
    group: unknown
    default:
    description: |

  - name: maxCostIncrease
    group: unknown
    default:
    description: |

  - name: maxFallHeightBucket
    group: unknown
    default:
    description: |

  - name: maxFallHeightNoWater
    group: unknown
    default:
    description: |

  - name: maxPathHistoryLength
    group: unknown
    default:
    description: |

  - name: mineDropLoiterDurationMSThanksLouca
    group: unknown
    default:
    description: |

  - name: mineGoalUpdateInterval
    group: unknown
    default:
    description: |

  - name: mineScanDroppedItems
    group: unknown
    default:
    description: |

  - name: minimumImprovementRepropagation
    group: unknown
    default:
    description: |

  - name: minYLevelWhileMining
    group: unknown
    default:
    description: |

  - name: mobAvoidanceCoefficient
    group: unknown
    default:
    description: |

  - name: mobAvoidanceRadius
    group: unknown
    default:
    description: |

  - name: mobSpawnerAvoidanceCoefficient
    group: unknown
    default:
    description: |

  - name: mobSpawnerAvoidanceRadius
    group: unknown
    default:
    description: |

  - name: movementTimeoutTicks
    group: unknown
    default:
    description: |

  - name: notificationOnBuildFinished
    group: unknown
    default:
    description: |

  - name: notificationOnExploreFinished
    group: unknown
    default:
    description: |

  - name: notificationOnFarmFail
    group: unknown
    default:
    description: |

  - name: notificationOnMineFail
    group: unknown
    default:
    description: |

  - name: notificationOnPathComplete
    group: unknown
    default:
    description: |

  - name: notifier
    group: unknown
    default:
    description: |

  - name: okIfAir
    group: unknown
    default:
    description: |

  - name: okIfWater
    group: unknown
    default:
    description: |

  - name: overshootTraverse
    group: unknown
    default:
    description: |

  - name: pathCutoffFactor
    group: unknown
    default:
    description: |

  - name: pathCutoffMinimumLength
    group: unknown
    default:
    description: |

  - name: pathHistoryCutoffAmount
    group: unknown
    default:
    description: |

  - name: pathingMapDefaultSize
    group: unknown
    default:
    description: |

  - name: pathingMapLoadFactor
    group: unknown
    default:
    description: |

  - name: pathingMaxChunkBorderFetch
    group: unknown
    default:
    description: |

  - name: pathRenderLineWidthPixels
    group: unknown
    default:
    description: |

  - name: pathThroughCachedOnly
    group: unknown
    default:
    description: |

  - name: pauseMiningForFallingBlocks
    group: unknown
    default:
    description: |

  - name: planAheadFailureTimeoutMS
    group: unknown
    default:
    description: |

  - name: planAheadPrimaryTimeoutMS
    group: unknown
    default:
    description: |

  - name: planningTickLookahead
    group: unknown
    default:
    description: |

  - name: preferSilkTouch
    group: unknown
    default:
    description: |

  - name: prefix
    group: unknown
    default:
    description: |

  - name: prefixControl
    group: unknown
    default:
    description: |

  - name: primaryTimeoutMS
    group: unknown
    default:
    description: |

  - name: pruneRegionsFromRAM
    group: unknown
    default:
    description: |

  - name: randomLooking
    group: unknown
    default:
    description: |

  - name: randomLooking113
    group: unknown
    default:
    description: |

  - name: renderCachedChunks
    group: unknown
    default:
    description: |

  - name: renderGoal
    group: unknown
    default:
    description: |

  - name: renderGoalAnimated
    group: unknown
    default:
    description: |

  - name: renderGoalIgnoreDepth
    group: unknown
    default:
    description: |

  - name: renderGoalXZBeacon
    group: unknown
    default:
    description: |

  - name: renderPath
    group: unknown
    default:
    description: |

  - name: renderPathAsLine
    group: unknown
    default:
    description: |

  - name: renderPathIgnoreDepth
    group: unknown
    default:
    description: |

  - name: renderSelection
    group: unknown
    default:
    description: |

  - name: renderSelectionBoxes
    group: unknown
    default:
    description: |

  - name: renderSelectionBoxesIgnoreDepth
    group: unknown
    default:
    description: |

  - name: renderSelectionCorners
    group: unknown
    default:
    description: |

  - name: renderSelectionIgnoreDepth
    group: unknown
    default:
    description: |

  - name: repackOnAnyBlockChange
    group: unknown
    default:
    description: |

  - name: replantCrops
    group: unknown
    default:
    description: |

  - name: replantNetherWart
    group: unknown
    default:
    description: |

  - name: rightClickContainerOnArrival
    group: unknown
    default:
    description: |

  - name: rightClickSpeed
    group: unknown
    default:
    description: |

  - name: schematicFallbackExtension
    group: unknown
    default:
    description: |

  - name: schematicOrientationX
    group: unknown
    default:
    description: |

  - name: schematicOrientationY
    group: unknown
    default:
    description: |

  - name: schematicOrientationZ
    group: unknown
    default:
    description: |

  - name: selectionLineWidth
    group: unknown
    default:
    description: |

  - name: selectionOpacity
    group: unknown
    default:
    description: |

  - name: settingTypes
    group: unknown
    default:
    description: |

  - name: shortBaritonePrefix
    group: unknown
    default:
    description: |

  - name: simplifyUnloadedYCoord
    group: unknown
    default:
    description: |

  - name: skipFailedLayers
    group: unknown
    default:
    description: |

  - name: slowPath
    group: unknown
    default:
    description: |

  - name: slowPathTimeDelayMS
    group: unknown
    default:
    description: |

  - name: slowPathTimeoutMS
    group: unknown
    default:
    description: |

  - name: splicePath
    group: unknown
    default:
    description: |

  - name: sprintAscends
    group: unknown
    default:
    description: |

  - name: sprintInWater
    group: unknown
    default:
    description: |

  - name: startAtLayer
    group: unknown
    default:
    description: |

  - name: strictLiquidCheck
    group: unknown
    default:
    description: |

  - name: toaster
    group: unknown
    default:
    description: |

  - name: toastTimer
    group: unknown
    default:
    description: |

  - name: useSwordToMine
    group: unknown
    default:
    description: |

  - name: verboseCommandExceptions
    group: unknown
    default:
    description: |

  - name: walkOnWaterOnePenalty
    group: unknown
    default:
    description: |

  - name: walkWhileBreaking
    group: unknown
    default:
    description: |

  - name: worldExploringChunkOffset
    group: unknown
    default:
    description: |

  - name: yLevelBoxSize
    group: unknown
    default:
    description: |
