# allowBreak
# allowBreakAnyway
# allowSprint
# allowPlace
# allowInventory
# assumeExternalAutoTool
# autoTool
# blockPlacementPenalty
# blockBreakAdditionalPenalty
# jumpPenalty
# walkOnWaterOnePenalty
# strictLiquidCheck
# allowWaterBucketFall
# assumeWalkOnWater
# assumeWalkOnLava
# assumeStep
# assumeSafeWalk
# allowJumpAt256
# allowParkourAscend
# allowDiagonalDescend
# allowDiagonalAscend
# allowDownward
# acceptableThrowawayItems
# blocksToAvoid
# blocksToDisallowBreaking
# blocksToAvoidBreaking
# avoidBreakingMultiplier
# buildIgnoreBlocks
# buildSkipBlocks
# buildValidSubstitutes
# buildSubstitutes
# okIfAir
# buildIgnoreExisting
# buildIgnoreDirection
# buildIgnoreProperties
# avoidUpdatingFallingBlocks
# allowVines
# allowWalkOnBottomSlab
# allowParkour
# allowParkourPlace
# considerPotionEffects
# sprintAscends
# overshootTraverse
# pauseMiningForFallingBlocks
# rightClickSpeed
# randomLooking113
# blockReachDistance
# randomLooking
# costHeuristic
# pathingMaxChunkBorderFetch
# backtrackCostFavoringCoefficient
# avoidance
# mobSpawnerAvoidanceCoefficient
# mobSpawnerAvoidanceRadius
# mobAvoidanceCoefficient
# mobAvoidanceRadius
# rightClickContainerOnArrival
# enterPortal
# minimumImprovementRepropagation
# cutoffAtLoadBoundary
# maxCostIncrease
# costVerificationLookahead
# pathCutoffFactor
# pathCutoffMinimumLength
# planningTickLookahead
# pathingMapDefaultSize
# pathingMapLoadFactor
# maxFallHeightNoWater
# maxFallHeightBucket
# allowOvershootDiagonalDescend
# simplifyUnloadedYCoord
# repackOnAnyBlockChange
# movementTimeoutTicks
# primaryTimeoutMS
# failureTimeoutMS
# planAheadPrimaryTimeoutMS
# planAheadFailureTimeoutMS
# slowPath
# slowPathTimeDelayMS
# slowPathTimeoutMS
# doBedWaypoints
# doDeathWaypoints
# chunkCaching
# pruneRegionsFromRAM
# backfill
# logAsToast
# toastTimer
# chatDebug
# chatControl
# chatControlAnyway
# renderPath
# renderPathAsLine
# renderGoal
# renderGoalAnimated
# renderSelectionBoxes
# renderGoalIgnoreDepth
# renderGoalXZBeacon
# renderSelectionBoxesIgnoreDepth
# renderPathIgnoreDepth
# pathRenderLineWidthPixels
# goalRenderLineWidthPixels
# fadePath
# freeLook
# antiCheatCompatibility
# pathThroughCachedOnly
# sprintInWater
# blacklistClosestOnFailure
# renderCachedChunks
# cachedChunksOpacity
# prefixControl
# prefix
# shortBaritonePrefix
# echoCommands
# censorCoordinates
# censorRanCommands
# itemSaver
# itemSaverThreshold
# preferSilkTouch
# walkWhileBreaking
# splicePath
# maxPathHistoryLength
# pathHistoryCutoffAmount
# mineGoalUpdateInterval
# maxCachedWorldScanCount
# minYLevelWhileMining
# allowOnlyExposedOres
# allowOnlyExposedOresDistance
# exploreForBlocks
# worldExploringChunkOffset
# exploreChunkSetMinimumSize
# exploreMaintainY
# replantCrops
# replantNetherWart
# extendCacheOnThreshold
# buildInLayers
# layerOrder
# layerHeight
# startAtLayer
# skipFailedLayers
# buildOnlySelection
# buildRepeat
# buildRepeatCount
# buildRepeatSneaky
# breakFromAbove
# goalBreakFromAbove
# mapArtMode
# okIfWater
# incorrectSize
# breakCorrectBlockPenaltyMultiplier
# schematicOrientationX
# schematicOrientationY
# schematicOrientationZ
# schematicFallbackExtension
# builderTickScanRadius
# mineScanDroppedItems
# mineDropLoiterDurationMSThanksLouca
# distanceTrim
# cancelOnGoalInvalidation
# axisHeight
# disconnectOnArrival
# legitMine
# legitMineYLevel
# legitMineIncludeDiagonals
# forceInternalMining
# internalMiningAirException
# followOffsetDistance
# followOffsetDirection
# followRadius
# disableCompletionCheck
# cachedChunksExpirySeconds
# logger
# notifier
# toaster
# verboseCommandExceptions
# yLevelBoxSize
# colorCurrentPath
# colorNextPath
# colorBlocksToBreak
# colorBlocksToPlace
# colorBlocksToWalkInto
# colorBestPathSoFar
# colorMostRecentConsidered
# colorGoalBox
# colorInvertedGoalBox
# colorSelection
# colorSelectionPos1
# colorSelectionPos2
# selectionOpacity
# selectionLineWidth
# renderSelection
# renderSelectionIgnoreDepth
# renderSelectionCorners
# useSwordToMine
# desktopNotifications
# notificationOnPathComplete
# notificationOnFarmFail
# notificationOnBuildFinished
# notificationOnExploreFinished
# notificationOnMineFail
# byLowerName
# allSettings
# settingTypes
